from enum import Enum

REQUEST_CURSOR = "cursor"
REQUEST_SORT = "sort"
REQUEST_PAGE = "page"
REQUEST_LIMIT = "limit"

# LOG
LOG_CTX_CID_KEY = "cid"
LOG_CTX_UNIQ_TNX_KEY = "tnx-id"

# RESPONSE HEADER
RESPONSE_HEADER_CID_KEY = "X-CID"
RESPONSE_HEADER_REQUEST_LENGTH_KEY = "content-length"
RESPONSE_HEADER_RESPONSE_TIME_KEY = "X-Response-Time"
RESPONSE_HEADER_RESPONSE_LENGTH_KEY = "content-length"


# STATUS CODE
STATUS_CODE_DEPENDENT_SERVICE = 521

# STATUS TYPE
STATUS_TYPE_SUCCESS = "SUCCESS"
STATUS_TYPE_ERROR = "ERROR"
STATUS_TYPE_WARN = "WARN"

# INTERNAL STATUS CODES
INTERNAL_ERROR_CODE_BAD_REQUEST = "400"
INTERNAL_ERROR_CODE_UNAUTHORIZED = "401"
INTERNAL_ERROR_CODE_FORBIDDEN = "403"
INTERNAL_ERROR_CODE_NOT_FOUND = "404"
INTERNAL_ERROR_CODE_VALIDATION_ERROR = "422"
INTERNAL_ERROR_CODE_SERVER_ERROR = "500"

# STATUS DESC
STATUS_DESC_SUCCESS = "Success"
STATUS_DESC_PARTIAL_SUCCESS = "Partial Success"
STATUS_DESC_NO_DATA = "No Data Found"
STATUS_DESC_INVALID_CREDENTIAL = "Invalid Credentials"
STATUS_DESC_INVALID_REQUEST = "Invalid Request"
STATUS_DESC_REQ_INFO = "Required Info Missing"
STATUS_DESC_REQ_PH_PASS = "Required Phone Number and Password"
STATUS_DESC_USR_NOT_ACTIVE = "User not active"
STATUS_DESC_USR_NOT_EXIST = "User not exist"
STATUS_DESC_ALREADY_EXIST = "Already Exist"
STATUS_DESC_AUTH_TOKEN_REQUIRED = "Required Authorization Token"
STATUS_DESC_AUTH_INVALID_TOKEN = "Invalid Token"
STATUS_DESC_AUTH_TOKEN_EXPIRED = "Token Expired"
STATUS_DESC_AUTH_TOKEN_INVALID_INFO = "Token has missing information"
STATUS_DESC_AUTH_INVALID_ACTION = "Invalid Action received"
STATUS_DESC_AUTH_NO_RESOURCE_ACCESS = "Action Not Permitted"
STATUS_DESC_AUTH_INVALID_ACCESS_TYPE = "Not Valid access type configured"
STATUS_DESC_AUTH_NOT_AUTHORIZED_FOR_ACTION = "Not Authorized to perform action"
STATUS_DESC_AUTH_INVALID_ROLE = "No Role or Action configured"
STATUS_DESC_DATABASE_EXCEPTION = "Database Exception"
STATUS_DESC_PGW_NO_RESPONSE = "No Response from"
STATUS_DESC_PGW_EXCEPTION = "PGW EXCEPTION"
STATUS_DESC_PGW_ERROR = "PGW Error"
STATUS_DESC_PGW_INVALID_PAYMENT_TYPE = "Invalid Payment Type"
STATUS_DESC_PGW_INVALID_PAYMENT = "Invalid Payment"
STATUS_DESC_NOT_IMPLEMENTED = "Not Implemented"
STATUS_DESC_NOT_FOUND = "Not Found"
STATUS_DESC_NOT_ALLOWED = "Not Allowed"
STATUS_DESC_NO_UPDATE_EXCEPTION = "Failed to Update"
STATUS_DESC_FAILED_EXEC = "Failed to Execute"
STATUS_DESC_FAILED_CREATE = "Failed to Create"
STATUS_DESC_INVALID_TYPE = "Invalid Type"
STATUS_DESC_INVALID_REQUEST_PARAM = "Invalid Request Param"

STATUS_DESC_NOTIFY_INVALID_CHANNEL = "Invalid Notification Channel"

# DATABASE MONGODB
COLL_TODO_APP_SECRET = "app_secret"
COLL_TODO_CUSTOMER = "customer"
COLL_TODO_MARKETING = "marketing"
COLL_TODO_PRODUCTION = "production"
COLL_TODO_DELIVERY = "delivery"
COLL_TODO_USER = "user"
COLL_TODO_OTP_DETAIL = "otp_detail"
COLL_TODO_PROFILE = "profile"
COLL_TODO_ORDER = "order"
COLL_TODO_ORDER_ITEM = "order_item"
COLL_TODO_PAYMENT = "payment"
COLL_TODO_ORDER_AUDIT = "order_audit"

COLL_TODO_SEQ_USER_ID = "app_sequence_user"
COLL_TODO_SEQ_PRODUCT_ID = "app_sequence_product"
COLL_TODO_SEQ_CUSTOMER_ID = "app_sequence_customer"
COLL_TODO_SEQ_MARKETING_ID = "app_sequence_marketing"
COLL_TODO_SEQ_PRODUCTION_ID = "app_sequence_production"
COLL_TODO_SEQ_DELIVERY_ID = "app_sequence_delivery"
COLL_TODO_SEQ_PROFILE_ID = "app_sequence_profile"
COLL_TODO_SEQ_ORDER_ID = "app_sequence_order"
COLL_TODO_SEQ_ORDER_ITEM_ID = "app_sequence_order_item"
COLL_TODO_SEQ_PAYMENT_ID = "app_sequence_payment"

SEQ_TODO_USER_ID = "user_id_seq"
SEQ_TODO_PRODUCT_ID = "product_id_seq"
SEQ_TODO_CUSTOMER_ID = "customer_id_seq"
SEQ_TODO_MARKETING_ID = "marketing_id_seq"
SEQ_TODO_PRODUCTION_ID = "production_id_seq"
SEQ_TODO_DELIVERY_ID = "delivery_id_seq"
SEQ_TODO_PROFILE_ID = "profile_id_seq"
SEQ_TODO_ORDER_ID = "order_id_seq"
SEQ_TODO_ORDER_ITEM_ID = "order_item_id_seq"
SEQ_TODO_PAYMENT_ID = "payment_id_seq"

PREFIX_SEQ_TODO_USER_ID = "U"
PREFIX_SEQ_TODO_CUSTOMER_ID = "C"
PREFIX_SEQ_TODO_MARKETING_ID = "MKT"
PREFIX_SEQ_TODO_PRODUCTION_ID = "P"
PREFIX_SEQ_TODO_DELIVERY_ID = "D"
PREFIX_SEQ_TODO_PROFILE_ID = "PF"
PREFIX_SEQ_TODO_ORDER_ID = "O"
PREFIX_SEQ_TODO_ORDER_ITEM_ID = "I"
PREFIX_SEQ_TODO_PAYMENT_ID = "PY"

KEY_ASSOCIATED_ID = "associated_id"
KEY_ASSOCIATED_TYPE = "associated_type"
KEY_ATTRIBUTE = 'attribute'
KEY_N_ALIAS_SRC_EVENT_ID = "source_event_id"

DOC_OBJ_ID = "_id"
PY_OBJ_ID = "id"

RES_C_KEY_DATA = "data"
RES_C_KEY_PAGINATION = "pagination"


# Query
Q_VALUE_NULL = "null"

Q_FILTER_OPR_EQUALS = "$eq"
Q_FILTER_OPR_GREATER_EQ = "$gte"
Q_FILTER_OPR_LESSER_EQ = "$lte"
Q_FILTER_OPR_GREATER = "$gt"
Q_FILTER_OPR_LESSER = "$lt"
Q_FILTER_OPR_IN = "$in"

Q_FILTER_EQUALS = "eq"
Q_FILTER_GREATER_EQ = "__gte"
Q_FILTER_LESSER_EQ = "__lte"
Q_FILTER_GREATER = "__gt"
Q_FILTER_LESSER = "__lt"
Q_FILTER_NULL = "__isnull"
Q_FILTER_IN = "__in"
Q_FILTER_EXACT = "__exact"
Q_FILTER_CONTAINS = "__contains"
Q_FILTER_CASE_IN_SENSITIVE_CONTAINS = "__icontains"
Q_FILTER_BOOLEAN = "Boolean"

Q_FILTER_CONDITION_AND = "$and"
Q_FILTER_CONDITION_OR = "$or"

Q_OPERATOR_UPDATE_DOLLAR = "$"
Q_OPERATOR_SET = "$set"
Q_DEFAULT_SEPERATOR_DOT = "."

Q_SORT_TYPE_ASC = "ASC"
Q_SORT_OPR_TYPE_ASC = "1"

Q_SORT_TYPE_DESC = "DESC"
Q_SORT_OPR_TYPE_DESC = "-1"

Q_AGG_TOTAL_COUNT = "total_count"

DEFAULT_DB_IS_PRESENT_LIMIT = 1
DEFAULT_DB_PAGE_SIZE = 5

# RBAC
RESOURCE_OWNER_ID = 'owner_id'
RESOURCE_ORG_ID = 'org_id'
RESOURCE_BODY_CREATED_BY = 'createdBy'
RESOURCE_BODY_UPDATED_BY = 'updatedBy'
RESOURCE_BODY_CREATED_ON = 'createdOn'
RESOURCE_BODY_UPDATED_ON = 'updatedOn'
RESOURCE_BODY_ORG_ID = 'orgId'
RESOURCE_BODY_OWNER_ID = 'ownerId'
RESOURCE_BODY_BUSINESS_UNIT_ID = 'businessUnitId'

# RBAC
RESOURCE_DB_OWNER_ID = 'owner_id'
RESOURCE_DB_ORG_ID = 'org_id'
RESOURCE_DB_CREATED_BY = 'created_by'
RESOURCE_DB_UPDATED_BY = 'updated_by'
RESOURCE_DB_CREATED_ON = 'created_on'
RESOURCE_DB_UPDATED_ON = 'updated_on'

RESOURCE_TYPE_PRODUCT = 'product'
RESOURCE_TYPE_USER = 'user'
RESOURCE_TYPE_CUSTOMER = 'customer'
RESOURCE_TYPE_MARKETING = 'marketing'
RESOURCE_TYPE_PRODUCTION = 'production'
RESOURCE_TYPE_DELIVERY = 'delivery'
RESOURCE_TYPE_DASHBOARD = 'dashboard'
RESOURCE_TYPE_PROFILE = 'profile'
RESOURCE_TYPE_ORDER = 'order'
RESOURCE_TYPE_PAYMENT = 'payment'

ACTION_TYPE_WRITE = 'write'
ACTION_TYPE_READ = 'read'
ACTION_TYPE_UPDATE = 'write'
ACTION_TYPE_DELETE = 'write'

KEY_N_ALIAS_UPDATED_ON = "updated_on"
KEY_N_ALIAS_UPDATED_BY = "updated_by"
KEY_N_ALIAS_ORG_ID = 'org_id'
KEY_N_ALIAS_CREATED_BY = 'created_by'
KEY_N_ALIAS_OWNER_ID = 'owner_id'

DOC_STORE = "s3"
DOC_UPLOAD = "upload"
DOC_DOWNLOAD = "download"

NO_AUTH_ANONYMOUS_USER_ID = "default-sys-user-id"
NO_AUTH_ANONYMOUS_ORG_ID = "default-sys-org-id"
NO_AUTH_ANONYMOUS_ROLE = ["anonymous-user"]
NO_AUTH_ANONYMOUS_EXPIRY = 1

INVALID_ARGUMENT_FOR_ARITHMETIC_OPR = "Invalid arguments for arithmetic"

DTO_KEY_RESPONSE_DATA = "response_data"

